---
title: "plots"
output: github_document
---

```{r}
library(tidyverse)
library(sf)
library(gridExtra)
all_critters <- read_csv("../data/all_critters_output2.csv")
pa_priority <- st_read("../data/pa_priority.shp")
ce_priority <- st_read("../data/ce_priority.shp")
```

```{r}
all_critters %>% filter(pa_ce == "Protected areas" | pa_ce == "Conservation Easements")
```

```{r}
#devtools::install_github("wilkelab/ungeviz")
```

```{r}
library(ungeviz)
```

```{r fig1, fig.height=4, fig.width=4, dpi = 600}
all_us_crits <- all_critters %>% filter(pa_ce == "all")


all_critters_plot <- all_critters %>% 
  filter(pa_ce == "Protected areas" | pa_ce == "Conservation Easements") %>%
  mutate(pa_ce = recode(pa_ce, `Protected areas` = "Protected areas", `Conservation Easements` = "Conservation \n easements")) 

ggplot() + 
  scale_fill_manual(values=c("#0072B2", "#E69F00")) +
  geom_bar(all_critters_plot, mapping = aes(x= crit, y= priority_i, fill = pa_ce),
                                  stat = "identity", width=0.65,
                                  position=position_dodge(width=0.8)) +
  geom_hpline(data = all_us_crits, aes(x=crit, y =priority_i), stat = "identity", height = 0.4, lwd = .75) +
  geom_point(all_us_crits, mapping = aes(x = crit, y= priority_i), pch = 19) +
  theme_minimal() +
  theme(axis.title.y =element_blank()) +
  theme(legend.title = element_blank()) + coord_flip() +
  theme(legend.position = c(0.75, 0.68)) +ylim(-0.1,1.2) +ylab("Priority Index") +
   theme(axis.text=element_text(size=8),
        axis.title=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"),
        legend.text = element_text(size = 8)) +
  guides(shape = guide_legend(override.aes = list(size = 5)))
 ## scale_y_continuous(0, 1, by = 0.5)
```



```{r}
pa_size<- as.tibble(pa_priority) %>%
  mutate(pa_ce = "pa") %>%
  group_by(WDPAID, pa_ce) %>%
  summarise(area = sum(area),
            priority = mean(Prirty_)) %>%
  mutate(unique_id = WDPAID)


ce_size<- as.tibble(ce_priority) %>%
  mutate(pa_ce = "ce") %>%
  group_by(uniqu_d, pa_ce) %>%
  summarise(area = sum(area),
            priority = mean(Prirty_)) %>%
  mutate(unique_id = uniqu_d)
```

```{r}
ce_size$unique_id <- as.numeric(ce_size$unique_id)
pa_size$unique_id <- as.numeric(pa_size$unique_id)

size_plot <- pa_size %>%
  bind_rows(ce_size) %>% 
  mutate(area = as.numeric(area)) %>%
  filter(priority <50)

size_plot %>% ggplot(aes(x = log(area), y = priority, col = pa_ce)) + geom_point(shape = 21,alpha = 1/5)
```
```{r}
pa_all<- as.tibble(pa_priority) %>%
  mutate(pa_ce = "pa",
         Priority_i = Prirty_) %>%
  group_by(pa_ce) %>%
  summarise(priority_i = sum(Priority_i*as.numeric(area)),
            area = sum(as.numeric(area)),
            .groups = "drop") %>% 
  mutate(priority_i = priority_i/area) 

ce_all<- as.tibble(ce_priority) %>%
  mutate(pa_ce = "ce",
         Priority_i = Prirty_) %>%
  group_by(pa_ce) %>%
  summarise(priority_i = sum(Priority_i*as.numeric(area)),
            area = sum(as.numeric(area)),
            .groups = "drop") %>% 
  mutate(priority_i = priority_i/area)

all_priority_i <- pa_all %>% bind_rows(ce_all) %>%
   mutate(crit = "all")
all_priority_i
```


```{r}
a <- size_plot %>% group_by(pa_ce) %>% summarise(area = sum(area)/10^9,
                                                 count = n()) %>%
  mutate(pa_ce = recode(pa_ce, pa = "Protected \nareas", ce = "Conservation \n Easements")) %>%
  ggplot(aes(x = pa_ce, y = area, fill = pa_ce)) + 
  scale_fill_manual(values=c("#0072B2", "#E69F00")) +
  geom_bar(stat = "identity", width=0.65, position=position_dodge(width=0.8)) +
  theme_minimal() +
 theme(axis.title.x =element_blank()) +
  theme(legend.title = element_blank()) + 
  theme(legend.position = "none") + ylab("Total area") +
   theme(axis.text=element_text(size=8),
        axis.title=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"))

b <- all_priority_i %>%
  mutate(pa_ce = recode(pa_ce, pa = "Protected \nareas", ce = "Conservation \n Easements")) %>%
  ggplot(aes(x = pa_ce, y =priority_i, fill = pa_ce)) +geom_bar(stat = "identity") %>%
  scale_fill_manual(values=c("#0072B2", "#E69F00")) +
  geom_bar(stat = "identity", width=0.65, position=position_dodge(width=0.8)) +
  theme_minimal() +
  theme(axis.title.x =element_blank()) +
  theme(legend.title = element_blank()) + 
  theme(legend.position = "none") + ylab("Mean priority index") + 
   theme(axis.text=element_text(size=8),
        axis.title=element_text(size=10),
        panel.border = element_rect(colour = "black", fill=NA),
        legend.box.background = element_rect(colour = "black"))
```

```{r, fig.height= 5, fig.width= 3, dpi= 600}
grid.arrange(a, b, nrow = 2)
```

```{r}
ce_priority_i <- as.tibble(ce_priority) %>%
  mutate(year_est = year_st,
         Priority_i = Prirty_) %>%
  group_by(year_est) %>%
  summarise(priority_i = sum(Priority_i*as.numeric(area)),
            area = sum(as.numeric(area)),
            .groups = "drop") %>% 
  mutate(priority_i = priority_i/area,
         pa_ce = "ce") %>%
  rename(STATUS_YR = "year_est")
```

```{r}
pa_priority_i <- as.tibble(pa_priority) %>%
  mutate(STATUS_YR = STATUS_,
         Priority_i = Prirty_) %>%
  group_by(STATUS_YR) %>%
  summarise(priority_i = sum(Priority_i*as.numeric(area)),
            area = sum(as.numeric(area)),
            .groups = "drop") %>% 
  mutate(priority_i = priority_i/area,
         pa_ce = "pa") 
```

```{r}
all_yrs <- pa_priority_i %>%
  bind_rows(ce_priority_i)
all_yrs <- as.data.frame(all_yrs)

 a<- all_yrs %>% filter(STATUS_YR >2000, STATUS_YR<2017) %>%
  ggplot(aes(x = STATUS_YR, y = priority_i, col = pa_ce)) +geom_line()
 
b<- all_yrs %>% filter(STATUS_YR>1980, STATUS_YR<2017) %>%
  ggplot(aes(x = STATUS_YR, y = area, col = pa_ce)) +geom_line()

grid.arrange(a, b, ncol = 1)

all_yrs %>% filter(STATUS_YR >1950) %>%
  group_by(pa_ce) %>%
  summarise(area = sum(area)/10^9)
```


```{r}
wdpa_usa <- st_read("../data/wdpa/wdpa_clean_usa.shp")
```

```{r}
ce <- st_read("../data/NCED_12182019_Shp/Conservation_Easements.shp")
```

```{r}
wdpa_map <- st_transform(wdpa_usa,st_crs(2163))
ce_map <- st_transform(ce,st_crs(2163))
```


```{r}
usa <- st_read("../data/usa_shp/gadm36_USA_0.shp")
```

```{r}
mainland <- ggplot() + 
  geom_sf(data = usa, fill = "#DCDCDC", lwd = 0)+
  geom_sf(data = ce_map, fill = "#0072B2",lwd = 0) +
  geom_sf(data = wdpa_map, fill = "#E69F00",lwd = 0) +
  coord_sf(crs = st_crs(2163), xlim = c(-2500000, 2500000), ylim = c(-2300000, 
         730000))+ theme_minimal() +
  theme(panel.border = element_rect(colour = "black", fill=NA))

mainland
```

```{r}
alaska <- ggplot() +
    geom_sf(data = usa, fill = "#DCDCDC", lwd = 0)+
     geom_sf(data = ce_map, fill = "#0072B2", lwd= 0) +
     geom_sf(data = wdpa_map, fill = "#E69F00", lwd = 0, alpha = 0.5) +
     coord_sf(crs = st_crs(3467), xlim = c(-2400000, 1600000), ylim = c(200000, 
         2500000), expand = FALSE, datum = NA) +theme_minimal() +
   theme(panel.border = element_rect(colour = "black", fill=NA))


hawaii  <- ggplot() +
    geom_sf(data = usa, fill = "#DCDCDC", lwd = 0)+
       geom_sf(data = ce_map, fill = "#0072B2", color = "#0072B2") +
       geom_sf(data = wdpa_map, fill = "#E69F00", color = "#E69F00") +
     coord_sf(crs = st_crs(4135), xlim = c(-161, -154), ylim = c(18, 
         23), expand = FALSE, datum = NA) +theme_minimal() +
     theme(panel.border = element_rect(colour = "black", fill=NA))


```


```{r, fig.height= 5, fi.width = 6, dpi = 600}
mainland +
 annotation_custom(
      grob = ggplotGrob(alaska),
      xmin = -2800000,
      xmax = -2750000 + (1600000 - (-2400000))/2.5,
      ymin = -2450000,
      ymax = -2450000 + (2500000 - 200000)/2.5
  ) +
  annotation_custom(
      grob = ggplotGrob(hawaii),
      xmin = -1250000,
      xmax = -1250000 + (-154 - (-161))*120000,
      ymin = -2450000,
      ymax = -2450000 + (23 - 18)*120000
  )
```


```{r}
regions <- st_read("../data/cb_2018_us_division_500k.shp")
```

(1) priorities ce and pa
(2) averages for regions
(4) maps

```{r}
ce <- st_transform(ce, crs = st_crs(amp_priority))
pa_priority <- st_intersection(st_buffer(wdpa_usa,0), st_buffer(priority_index,0))

am_ce <- st_intersection(st_buffer(ce,0), st_buffer(amp_priority,0))

```

```{r}
ce_priority<- st_read("../data/ce_priority.shp")
pa_priority <-st_read("../data/pa_priority.shp")
```

```{r}
ce_priority_i <- as.tibble(ce_priority) %>%
  group_by(year_st) %>%
  summarise(priority_i = sum(Prirty_*as.numeric(area)),
            area = sum(as.numeric(area)),
            .groups = "drop") %>% 
  mutate(priority_i = priority_i/area,
         pa_ce = "ce") %>%
  rename(STATUS_ = "year_st")
```

```{r}
pa_priority_i <- as.tibble(pa_priority) %>%
  group_by(STATUS_) %>%
  summarise(priority_i = sum(Prirty_*as.numeric(area)),
            area = sum(as.numeric(area)),
            .groups = "drop") %>% 
  mutate(priority_i = priority_i/area,
         pa_ce = "pa") 
pa_priority_i
```

```{r}
a<- pa_priority_i %>%
  bind_rows(ce_priority_i) %>%
  filter(STATUS_ > 2010) %>%
  group_by(pa_ce) %>%
  summarise(priority_i = sum(priority_i*as.numeric(area)),
            area = sum(as.numeric(area)),
            unweighted = mean(priority_i),
            .groups = "drop") %>%
  mutate(priority_i = priority_i/area) %>%
  ggplot(aes(x = pa_ce, y =unweighted)) +geom_bar(stat = "identity") +
  


b <- pa_priority_i %>%
  bind_rows(ce_priority_i) %>%
  filter(STATUS_<2011) %>%
  group_by(pa_ce) %>%
  summarise(priority_i = sum(priority_i*as.numeric(area)),
            area = sum(as.numeric(area)),
            .groups = "drop") %>%
  mutate(priority_i = priority_i/area) %>%
  ggplot(aes(x = pa_ce, y =priority_i)) +geom_bar(stat = "identity") 

```

