---
title: "wdpa"
author: "Millie Chapman"
date: "2/21/2020"
output: github_document
---

```{r setup, include=FALSE}
# load packages
library(tidyverse)
library(dplyr)
library(gridExtra)
library(ggmap)
library(ggpubr)
library(sf)
```


```{r}
cpad <- st_read("../data/CPAD_2020a/CPAD_2020a_Units.shp")
cpad %>% filter(YR_EST >1990) %>% select(UNIT_ID)  %>%plot()
```

```{r}
cced <- st_read("../data/CCED_2020a/CCED_2020a.shp")
cced %>% filter(year_est >1990) %>% select(cced_id) %>% plot()
```

```{r}
sig_hab <- st_read("../data/Terrestrial_Significant_Habitats_Summary_-_ACE_[ds2721]-shp/Terrestrial_Significant_Habitats_Summary_-_ACE_[ds2721].shp")

sig_hab <- as.tibble(sig_hab) %>%
  select(Hex_ID, TerrHabRan, TerrHabTot)
```

```{r}
connectivity <- st_read("../data/Terrestrial_Connectivity_-_ACE_[ds2734]-shp/")
```

```{r}
connectivity %>% filter(County == "ALAMEDA") %>% select(OBJECTID) %>% plot()
```

transform

```{r}
cced <- st_transform(cced, 4326)
cpad <- st_transform(cpad, 4326)
```

```{r cache = TRUE}
int_c_pa <- as_tibble(st_intersection(connectivity, cpad))
int_c_pa %>% filter(County == "MONTEREY") %>% select(geometry) %>% plot()
ccedb<- st_buffer(cced, dist = 0)
int_c_ce <- as_tibble(st_intersection(connectivity, ccedb))
int_c_ce %>% filter(County == "ALAMEDA") %>% select(geometry) %>% plot()
```

```{r}
int_c_ce$ce_area<- st_area(int_c_ce$geometry)

int_c_pa$pa_area<- st_area(int_c_pa$geometry)
```

```{r}
biodiversity <- st_read("../data/Species_Biodiversity_-_ACE_%5Bds2769%5D-shp/Species_Biodiversity_-_ACE_%5Bds2769%5D.shp")

biodiversity <- as.tibble(biodiversity) 

biodiv <- biodiversity %>%
  select(Hex_ID, NtvSpRnkEc, RarRnkEco, TerrClimRa, SpBioRnkEc)
```

```{r}
paArea <- int_c_pa %>%
  group_by(Hex_ID) %>%  
  mutate(pa_area = as.numeric(pa_area)) %>%
  summarise(paArea = sum(pa_area))

ceArea <- int_c_ce %>%
  group_by(Hex_ID) %>%
  mutate(ce_area = as.numeric(ce_area)) %>%
  summarise(ceArea = sum(ce_area))
```

```{r}
all <- connectivity %>%
  left_join(ceArea) %>%
  left_join(paArea) 
 
all$tot_area <- st_area(all$geometry)

all <- all %>%
  mutate(tot_area = as.numeric(tot_area)) 

all <- all %>%
  left_join(sig_hab) %>%
  left_join(biodiv) %>%
  mutate(perc_pa = paArea/tot_area,
         perc_ce = ceArea/tot_area) %>%
  mutate(perc_pa = replace_na(perc_pa, 0),
         perc_ce = replace_na(perc_ce, 0))

areace <- sum(all$ceArea, na.rm = TRUE)
areapa <- sum(all$paArea, na.rm = TRUE)
areaca <- sum(all$tot_area, na.rm = TRUE)
```

```{r}
habitat_total <- as.tibble(all) %>% select(TerrHabTot, paArea, ceArea, tot_area) %>%
  group_by(TerrHabTot) %>%
  summarise(perc_pa = sum(paArea, na.rm = TRUE)/areapa,
            perc_ce = sum(ceArea, na.rm = TRUE)/areace,
            california = sum(tot_area)/areaca) %>%
  pivot_longer(-TerrHabTot, names_to = "protection", values_to = "percent_area")
```

```{r}
connectivity_total <- as.tibble(all) %>% select(Connectivi, paArea, ceArea, tot_area) %>%
  group_by(Connectivi) %>%
  summarise(perc_pa = sum(paArea, na.rm = TRUE)/areapa,
            perc_ce = sum(ceArea, na.rm = TRUE)/areace,
            california = sum(tot_area)/areaca) %>%
  pivot_longer(-Connectivi, names_to = "protection", values_to = "percent_area")
```

```{r}
richness_total <- as.tibble(all) %>% select(SpBioRnkEc, paArea, ceArea, tot_area) %>%
  group_by(SpBioRnkEc) %>%
  summarise(perc_pa = sum(paArea, na.rm = TRUE)/areapa,
            perc_ce = sum(ceArea, na.rm = TRUE)/areace,
            california = sum(tot_area)/areaca) %>%
  pivot_longer(-SpBioRnkEc, names_to = "protection", values_to = "percent_area")
```

```{r}
nativesp_total <- as.tibble(all) %>% select(NtvSpRnkEc, paArea, ceArea, tot_area) %>%
  group_by(NtvSpRnkEc) %>%
  summarise(perc_pa = sum(paArea, na.rm = TRUE)/areapa,
            perc_ce = sum(ceArea, na.rm = TRUE)/areace,
            california = sum(tot_area)/areaca) %>%
  pivot_longer(-NtvSpRnkEc, names_to = "protection", values_to = "percent_area")
```

```{r}
h <- habitat_total %>% ggplot(aes(x = TerrHabTot, y = percent_area, color = protection))  + 
  geom_line(aes(linetype=protection)) + theme_minimal() + scale_color_manual(values=c("black", "blue", "orange")) +   scale_linetype_manual(values=c("dashed", "solid", "solid"))+
  labs( x="Total significant habitat coverage count", y = "Mean percent covered \n by protected areas")

c <-connectivity_total %>% ggplot(aes(x = Connectivi, y = percent_area, color = protection))  + 
  geom_line(aes(linetype=protection)) + theme_minimal() + scale_color_manual(values=c("black", "blue", "orange")) +   scale_linetype_manual(values=c("dashed", "solid", "solid"))+
  labs( x="Total significant connectivity", y = "Mean percent covered \n by protected areas")

r <-richness_total %>% ggplot(aes(x = SpBioRnkEc, y = percent_area, color = protection))  + 
  geom_line(aes(linetype=protection)) + theme_minimal() + scale_color_manual(values=c("black", "blue", "orange")) +   scale_linetype_manual(values=c("dashed", "solid", "solid"))+
  labs( x="Total significant SpBioRnkEc", y = "Mean percent covered \n by protected areas")
 
n <-nativesp_total %>% ggplot(aes(x = NtvSpRnkEc, y = percent_area, color = protection))  + 
  geom_line(aes(linetype=protection)) + theme_minimal() + scale_color_manual(values=c("black", "blue", "orange")) +   scale_linetype_manual(values=c("dashed", "solid", "solid"))+
  labs( x="Total significant SpBioRnkEc", y = "Mean percent covered \n by protected areas")

ggarrange(h,c,r,n, ncol = 2, nrow = 2, common.legend = TRUE)

```




```{r}
int_c_pa_all <- int_c_pa %>%
  full_join(as.tibble(biodiv)) %>%
  full_join(as.tibble(sig_hab)) %>%
  mutate(TerrHabTot = replace_na(TerrHabTot, 0))
  

int_c_ce_all <- int_c_ce %>%
  left_join(biodiv, by = "Hex_ID") %>%
  left_join(sig_hab, by = "Hex_ID") %>%
  mutate(TerrHabTot = replace_na(TerrHabTot, 0))


paArea_yr <- int_c_pa_all %>% 
  mutate(pa_area = as.numeric(pa_area)) %>%
  group_by(UNIT_ID, YR_EST) %>%  
  summarise(paArea = sum(pa_area),
            connectivity = mean(Connectivi),
            sig_hab = mean(TerrHabTot),
            richness = mean(SpBioRnkEc),
            nativesp = mean(NtvSpRnkEc)) %>%
  filter(YR_EST > 1979) %>%
 # mutate(area_connect = paArea*connectivity) %>%
  group_by(YR_EST) %>%
  summarise(connectivity = sum(paArea*connectivity),
            sig_hab = sum(paArea*sig_hab),
            richness = sum(paArea*richness),
            nativesp = sum(paArea*nativesp),
            paArea = sum(paArea)) %>%
  mutate(mean_connect = connectivity/paArea,
         mean_sighab = sig_hab/paArea,
         mean_richness = richness/paArea,
         mean_nativesp = nativesp/paArea,
         pa_ce = "PA") %>%
  select(YR_EST, mean_connect, mean_sighab,
         mean_nativesp,mean_richness, pa_ce)



ceArea_yr <- int_c_ce_all %>%
  mutate(ce_area = as.numeric(ce_area)) %>%
  group_by(cced_id, year_est) %>%  
  summarise(ceArea = sum(ce_area),
            connectivity = mean(Connectivi),
            sig_hab = mean(TerrHabTot),
            richness = mean(SpBioRnkEc),
            nativesp = mean(NtvSpRnkEc)) %>%
  filter(year_est > 1979) %>%
  mutate(YR_EST = year_est) %>%
  group_by(YR_EST) %>%
  summarise(connectivity = sum(ceArea*connectivity),
            sig_hab = sum(ceArea*sig_hab),
            richness = sum(ceArea*richness),
            nativesp = sum(ceArea*nativesp),
            ceArea = sum(ceArea)) %>%
  mutate(mean_connect = connectivity/ceArea,
         mean_sighab = sig_hab/ceArea,
         mean_richness = richness/ceArea,
         mean_nativesp = nativesp/ceArea,
         pa_ce = "ce") %>%
  select(YR_EST, mean_connect, mean_sighab,
         mean_nativesp,mean_richness, pa_ce)


metrics_yr <- ceArea_yr %>% 
  bind_rows(paArea_yr) 
```

```{r}
c_yr <- metrics_yr %>%
  ggplot(aes(x = YR_EST, y = mean_connect, color = pa_ce))  + 
  geom_line() + theme_minimal() + scale_color_manual(values=c("blue", "orange")) +   
  labs( x="Year", y = "Mean connectivity")

n_yr <- metrics_yr %>%
  ggplot(aes(x = YR_EST, y = mean_nativesp, color = pa_ce))  + 
  geom_line() + theme_minimal() + scale_color_manual(values=c("blue", "orange")) +   
  labs( x="Year", y = "Mean native spp ranking")

r_yr <- metrics_yr %>% 
  ggplot(aes(x = YR_EST, y = mean_richness, color = pa_ce))  + 
  geom_line() + theme_minimal() + scale_color_manual(values=c("blue", "orange")) +   
  labs( x="Year", y = "Mean richness ranking")

h_yr <- metrics_yr %>% 
  ggplot(aes(x = YR_EST, y = mean_sighab, color = pa_ce))  + 
  geom_line() + theme_minimal() + scale_color_manual(values=c("blue", "orange")) +   
  labs( x="Year", y = "Mean sig habitat ranking")

ggarrange(h_yr,c_yr,r_yr,n_yr, ncol = 2, nrow = 2, common.legend = TRUE)
```


